-- Configure each plugins
require("plugins.gitsigns")
require("plugins.which-key")
require("plugins.greeter")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.mason")
require("plugins.nvim-lint")
require("plugins.mason-nvim-lint")
require("plugins.conform")
require("plugins.neodev")
require("plugins.nvim-cmp")
require("plugins.nvterm")
require("plugins.glow")
require("plugins.symbols-outline")
-- require('plugins.nvim-tree')
require("plugins.lualine")
require("plugins.comment")
require("plugins.indent-blankline")
